#!/usr/bin/env python

# Author : Chayapol Piyaphakdeesakun

import rospy
from sensor_msgs.msg import LaserScan
from geometry_msgs.msg import Twist
from nav_msgs.msg import Odometry
from sensor_msgs.msg import MagneticField
import atexit

pub = ''

class Obstacle():
	def __init__(self):
		self.LIDAR_ERR = 0.05
		self._cmd_pub = rospy.Publisher('cmd_vel', Twist, queue_size=10)
		global pub
		pub = self._cmd_pub
		self.obstacle()

	def get_scan(self):
		msg = rospy.wait_for_message("scan", LaserScan)
		self.scan_filter = []
		for i in range(360):
			if i <= 15 or i > 335:
				if msg.ranges[i] >= self.LIDAR_ERR:
					self.scan_filter.append(msg.ranges[i])

	def get_odom(self):
		msg = rospy.wait_for_message("odom", Odometry)
		self.twist1 = msg.twist.twist.linear.x
		self.twist2 = msg.twist.twist.linear.y

		self.twist3 = msg.twist.twist.angular.z

	def get_mag(self):
		msg = rospy.wait_for_message("magnetic_field", MagneticField)
		self.mag_x = msg.magnetic_field.x
		self.mag_y = msg.magnetic_field.y
		self.mag_z = msg.magnetic_field.z

	def obstacle(self):
		self.twist = Twist()

		while not rospy.is_shutdown():
			try:
				#self.get_scan()

				self.get_odom()
				#print("Odometry:linear")
				#print(self.twist1)
				#print(self.twist2)
				#print("Odometry:angular")
				#print(self.twist3)

				self.get_mag()
				print("MagneticField")
				print(self.mag_x)
				print(self.mag_y)
				print(self.mag_z)

				#print("LaserScan")
				#print(min(self.scan_filter))
				#if min(self.scan_filter) < 0.33:
					#self.twist.linear.x = 0.0
				#else :	
					
					#self.twist.linear.x = 0.5
				self.twist.angular.z = 0.1
				self._cmd_pub.publish(self.twist)
			except KeyboardInterrupt:
				stop()

def stop():
	print('Stopping robot')
	twist = Twist()
	twist.linear.x = 0.0
	twist.angular.z = 0.0
	pub = rospy.Publisher('cmd_vel', Twist, queue_size=1)
	pub.publish(twist)

def main():
	rospy.init_node('run')
	rospy.on_shutdown(stop)

	try:
		obstacle = Obstacle()
	except rospy.ROSInterruptException:
		pass
if __name__ == '__main__':
	atexit.register(stop)
	main()
