#!/usr/bin/env python

# Author : Chayapol Piyaphakdeesakun

import rospy
from sensor_msgs.msg import LaserScan
from geometry_msgs.msg import Twist
from nav_msgs.msg import Odometry
from sensor_msgs.msg import MagneticField
from turtlebot3_msgs.msg import Sound
from time import sleep
import atexit
import math
import filetest
import icp
pub = ''
allscandata=""
class Obstacle():
	def __init__(self):
		self.LIDAR_ERR = 0.05
		self._cmd_pub = rospy.Publisher('cmd_vel', Twist, queue_size=10)
		self._sound_pub = rospy.Publisher('sound', Sound, queue_size=10)
		global pub
		allScanList=[]
		pub = self._cmd_pub
		global pub2
		pub2 = self._sound_pub
		self.obstacle()

	def get_scan(self):
		msg = rospy.wait_for_message("scan", LaserScan)
		self.scan_filter = []
		for i in range(360):
			self.scan_filter.append(msg.ranges[i])

	def get_odom(self):
		msg = rospy.wait_for_message("odom", Odometry)
		self.odom_pos_x = msg.pose.pose.position.x
		self.odom_pos_y = msg.pose.pose.position.y
		self.odom_ori_z = msg.pose.pose.orientation.z


	def obstacle(self):
		self.twist = Twist()
		allScandata=""
		while not rospy.is_shutdown():
			try:
				scanlist =[]
				self.get_scan()

				self.get_odom()

				#print("keisan:"+str(math.atan2(self.odom_pos_y, self.odom_pos_x)))
				#print("ori:"+str(self.odom_ori_z))
				scanlist += [self.odom_pos_x, self.odom_pos_y, math.atan2(self.odom_pos_y, self.odom_pos_x)+self.odom_ori_z]
				scanlist +=self.scan_filter

				scandata=" ".join(map(str, scanlist))+ "\n"


				global allscandata
				allscandata +=scandata
				print(allscandata)
				sleep(0.5)

			except KeyboardInterrupt:
				filetest.scan_write(allscandata)
				icp.scanmatch()
				stop()


def stop():
	print('Stopping robot')
	twist = Twist()
	twist.linear.x = 0.0
	twist.angular.z = 0.0
	pub = rospy.Publisher('cmd_vel', Twist, queue_size=1)
	pub.publish(twist)

def main():
	rospy.init_node('run')
	rospy.on_shutdown(stop)

	try:
		obstacle = Obstacle()
	except rospy.ROSInterruptException:
		pass
if __name__ == '__main__':
	atexit.register(stop)
	main()
